---
platform: linux

image_resource:
  type: docker-image
  source: {repository: cloudfoundrylondon/backup-and-restore}

inputs:
- name: disaster-recovery-acceptance-tests
  path: src/github.com/pivotal-cf-experimental/disaster-recovery-acceptance-tests
- name: bosh-backup-and-restore-meta
- name: bbr-binary-release

params:
  TEAM_GPG_KEY:
  BOSH_CLIENT_SECRET:
  DEPLOYMENT_TO_BACKUP:
  DEPLOYMENT_TO_RESTORE:
  BOSH_CLIENT:

run:
  path: src/github.com/pivotal-cf-experimental/disaster-recovery-acceptance-tests/ci/scripts/acceptance.sh
